from enum import Enum


class StockCode(Enum):
    # VN30:
    ACB = "ACB"
    BCM = "BCM"
    BID = "BID"
    BVH = "BVH"
    CTG = "CTG"
    FPT = "FPT"
    GAS = "GAS"
    GVR = "GVR"
    HDB = "HDB"
    HPG = "HPG"
    MBB = "MBB"
    MSN = "MSN"
    MWG = "MWG"
    NVL = "NVL"
    PDR = "PDR"
    PLX = "PLX"
    POW = "POW"
    SAB = "SAB"
    SSI = "SSI"
    STB = "STB"
    TCB = "TCB"
    TPB = "TPB"
    VCB = "VCB"
    VHM = "VHM"
    VIB = "VIB"
    VIC = "VIC"
    VJC = "VJC"
    VNM = "VNM"
    VPB = "VPB"
    VRE = "VRE"
