import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Head>
          <Script src="https://unpkg.com/htmx.org@1.9.4" />
          <meta charSet="utf-8" />
          <script
            src="https://unpkg.com/htmx.org@1.9.4"
            integrity="sha384-zUfuhFKKZCbHTY6aRR46gxiqszMk5tcHjsVFxnUo8VMus4kHGVdIYVbOYYNlKmHV"
            crossOrigin="anonymous"
          ></script>
        </Head>
        <Script src="https://unpkg.com/htmx.org@1.9.4" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
